#!/usr/bin/env python3
"""Regenerate web/static/js/gameicons.js from game-icons.net.

Grimoire uses two icon systems. Shikashi's 32px sprites carry anything with
room to breathe; these vectors carry everything that must be small or must
take the corpus accent colour, since 32px pixel art cannot be downscaled
without turning to mush.

The upstream SVGs are a black background rect plus a white glyph path. We keep
only the glyph geometry — the `d` strings — so the shipped module is pure path
data with no markup to inject, and the rendered icon inherits `currentColor`.

    python3 scripts/fetch-gameicons.py

Icons are CC BY 3.0; the per-icon author is recorded alongside the path so
ATTRIBUTIONS.md can be checked against what actually ships.
"""

import os
import re
import sys
import urllib.request

BASE = "https://raw.githubusercontent.com/game-icons/icons/master"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "web", "static", "js", "gameicons.js")

# name in Grimoire -> upstream author/icon
ICONS = {
    # chrome affordances
    "menu":       "delapouite/hamburger-menu",
    "collapse":   "delapouite/previous-button",
    "close":      "lorc/cross-mark",
    "rename":     "lorc/quill-ink",
    "delete":     "delapouite/trash-can",
    "mic":        "delapouite/microphone",
    "send":       "lorc/paper-arrow",
    "stop":       "delapouite/stop-sign",
    "settings":   "lorc/gears",
    "search":     "lorc/magnifying-glass",
    # modes and corpora
    "ask":        "delapouite/chat-bubble",
    "resolve":    "lorc/crystal-ball",
    "sage":       "lorc/wizard-staff",
    "mtg":        "lorc/book-aura",
    "dnd":        "delapouite/dice-twenty-faces-twenty",
    "swords":     "lorc/crossed-swords",
    "signout":    "lorc/candle-flame",
    # empty states and flourishes
    "no-history": "lorc/book-cover",
    "no-results": "lorc/scroll-unfurled",
    "thinking":   "lorc/circle-sparks",
    "spark":      "lorc/star-swirl",
    "wand":       "lorc/fairy-wand",
}

# The 512x512 background rect every upstream icon opens with.
BACKDROP = re.compile(r'^M0 0h512v512H0z$')
PATH_D = re.compile(r'<path[^>]*\sd="([^"]+)"')


def fetch(slug):
    with urllib.request.urlopen(f"{BASE}/{slug}.svg", timeout=20) as r:
        return r.read().decode("utf-8")


def glyph(svg, slug):
    paths = [d for d in PATH_D.findall(svg) if not BACKDROP.match(d.strip())]
    if not paths:
        sys.exit(f"{slug}: no glyph path found")
    return paths


def main():
    icons, credits = {}, {}
    for name, slug in sorted(ICONS.items()):
        icons[name] = glyph(fetch(slug), slug)
        credits[name] = slug
        print(f"  {name:11s} <- {slug}")

    def js_obj(d, fmt):
        rows = ",\n".join(f'\t"{k}": {fmt(v)}' for k, v in d.items())
        return "{\n" + rows + ",\n}"

    body = f"""// Generated by scripts/fetch-gameicons.py — do not edit by hand.
//
// Glyph geometry from game-icons.net (CC BY 3.0), by the authors named in
// CREDITS below. Only the path data ships: icons.js builds the <svg> around
// it, so every icon inherits currentColor and stays crisp at any size.

/** name -> array of SVG path `d` strings, on a 0 0 512 512 viewBox. */
export const GAME_ICONS = Object.freeze({js_obj(icons, lambda v: "[" + ", ".join(f'"{p}"' for p in v) + "]")});

/** name -> "author/icon" upstream, for attribution. */
export const CREDITS = Object.freeze({js_obj(credits, lambda v: f'"{v}"')});
"""
    open(OUT, "w").write(body)
    size = os.path.getsize(OUT)
    print(f"\nwrote {OUT} ({size // 1024}KB, {len(icons)} icons)")


if __name__ == "__main__":
    main()
